Repository braingourmets/crud, pull requests merged in 2022-07, with the labels that each got.

#337 [FEATURE] Add and use cssbundling-rails for SCSS
  .dockerdev/compose.yml
  .gitignore
  Gemfile
  Gemfile.lock
  app/assets/builds/.keep
  app/assets/config/manifest.js
  app/assets/stylesheets/application.sass.scss
  app/packs/entrypoints/application.js
  app/packs/entrypoints/application.scss
  app/views/layouts/application.html.haml
  config/initializers/assets.rb
  package.json
Labels: enhancement

#339 [BUGFIX] Security-update to Rails 6.1.6.1
  Gemfile
  Gemfile.lock
Labels: bug, dependencies

#346 [FEATURE] Add jsbundling-rails for JavaScript bundles
  .dockerdev/compose.yml
  Gemfile
  Gemfile.lock
  app/javascript/application.js
  app/views/layouts/application.html.haml
  package.json
  yarn.lock
Labels: enhancement

#347 [CLEANUP] Remove Webpacker
  .dockerdev/compose.yml
  .github/dependabot.yml
  .gitignore
  Gemfile
  Gemfile.lock
  README.md
  app/packs/entrypoints/application.js
  babel.config.js
  bin/webpack
  bin/webpack-dev-server
  config/webpack/base.js
  config/webpack/development.js
  config/webpack/environment.js
  config/webpack/production.js
  config/webpack/test.js
  config/webpacker.yml
  package.json
  yarn.lock
Labels: cleanup

#348 [TASK] Upgrade to psych 4
  .github/dependabot.yml
  Gemfile
  Gemfile.lock
Labels: dependencies
